feat: button 컴포넌트 구현 #11
ForFunGyeol/frontend pull request #18
Opened 2024-01-18 11:51 UTC by Leezero3

## #️⃣ 연관된 이슈

#11 

## 📝 작업 내용

- Button 컴포넌트에 대해 다크모드와 라이트모드 지원을 구현했습니다.
- 다크모드 위해 적용해주신 next-themes를 참조하여 작업하였습니다. (감사합니다 😆)
- 색상은 transparent / black / gray / pink, 사이즈는 가장 많이 사용되는 w-[335px]를 default로 설정하였습니다.

## 💬 리뷰어에게
-버튼의 디자인이 다양하여 현재는 lineHeight를 16px, width를 335px로 설정하였습니다. 추후 디자인이 완성되면 공통적으로 많이 사용되는 사이즈가 있으면 추가하겠습니다! 
- 버튼 클릭시 적용되는 효과가 있을 것 같은데 알아본 후 추가하도록 하겠습니다. 

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2024-01-18 12:25 UTC, thyeone reviewed
코멘트 확인 부탁드릴게요

2024-01-18 12:25 UTC, thyeone commented on src/components/common/button.tsx
> +  const sizeClass = size === 'default' ? 'w-[335px]' : '';
가로 길이를 335px 고정값으로 주게 되면 화면 크기가 더 큰 디바이스에서 대응이 안됩니다.
width:100%과 x축 마진을 줍시다

https://github.com/ForFunGyeol/frontend/assets/48711263/de089641-e552-43d2-95a3-a7a29f5b2001

2024-01-18 12:25 UTC, thyeone commented on src/components/common/button.tsx
> +  className?: string;
gray를 disabled props랑 연결하는 게 직관적이라고 생각해요. props로 내려준다고 생각해보면

``` tsx
const [disabled, setDisabled] = useState(false)

<Button color={isDisabled ? 'gray' : 'black'}>다음<Button/> 
```
이것보다
``` tsx
<Button disabled={disabled}>다음<Button/> 
```

처럼 하고 세부 구현은 안에 꽁쳐두는 게 더 효율적이라고 생각합니다

2024-01-18 12:25 UTC, thyeone commented on src/components/common/button.tsx
> +        'rounded-lg border border-solid px-4 py-2 text-sm transition duration-300',
디자인 확인해주세요 제가 확인한 건 폰트 굵기와 height 속성입니다

2024-01-18 12:25 UTC, thyeone commented on src/components/common/button.tsx
> +  const colorClass = isDark ? buttonColors[color].dark : buttonColors[color].default;
isDark props는 현재 이 페이지에서 다크모드가 적용될 수 있는 페이지인지를 의미합니다. 이처럼 분기처리하게 되면 사용자가 테마를 변경했을 때 대응할 수 없어지겠죠? 이전 PR처럼 `dark:`로 스타일링 부탁드립니다

2024-01-18 12:25 UTC, thyeone commented on src/components/common/button.tsx
> +  onClick?: () => void;
className과 onClick을 일일이 props로 받아올 필요없이 타입에 버튼 attribute 상속해서 rest로 가져올 수 있습니다

2024-01-18 12:25 UTC, thyeone commented on src/components/common/button.tsx
> +};
변수로 할당하는 스타일링은 최대한 지양해주세요. 현재는 클라이언트 컴포넌트라서 문제는 없어보이지만 서버 컴포넌트의 경우 문제가 발생될 여지가 보입니다 cn으로 조건부 스타일링 부탁드려요

그리고 pink는 전역적으로 사용된다고 보기 어려워서 별도로 빼는 게 좋을 것 같아요. 버튼 컴포넌트에서 너무 많은 걸 책임하고 있거든요

버튼 종류는 이렇게 3가지로만 분류해보는걸로 할까요?
![image](https://github.com/ForFunGyeol/frontend/assets/48711263/50b9e140-ed78-4211-988a-fcf63500201a)
![image](https://github.com/ForFunGyeol/frontend/assets/48711263/8f2b8453-6367-4e23-baf4-f77ff83fd119)
![image](https://github.com/ForFunGyeol/frontend/assets/48711263/eab8c406-e3ed-438a-aad1-3ea9e9901daf)

2024-01-18 12:25 UTC, thyeone commented on src/components/common/button.tsx
> +  transparent: {
저라면 화이트로 스타일링 했을 것 같은데 무드보드 페이지를 고려하면 투명이 더 적합해보이네요~! 👍

2024-01-19 05:00 UTC, thyeone commented on src/components/common/button.tsx
> +  const sizeClass = size === 'default' ? 'w-[335px]' : '';
아 죄송합니다 마진값은 주면 안될 것 같아요

2024-01-19 09:24 UTC, Leezero3 commented on src/components/common/button.tsx
> +  className?: string;
미처 확인하지 못한 부분인 것 같아요. 체크해주셔서 감사합니다!
피그마에 각 버튼의 default / disabled / pressed 상태가 업데이트 되어서 해당 부분 수정 후 반영 하도록 하겠습니다!

2024-01-23 05:07 UTC, thyeone requested changes

2024-01-23 05:07 UTC, thyeone commented on src/components/common/button.tsx
> +  };
피그마 디자인에는 pressed로 명시되어 있긴 하지만 hover일 가능성도 있는 것 같아요.. 여쭤보시는 게 좋을 것 같습니다

2024-01-23 05:07 UTC, thyeone commented on src/components/common/button.tsx
> +        size === 'full' ? 'w-full' : '',
이메일 로그인 페이지 삭제되면서 full만 사용하면 될 것 같네요
&&처럼 표시하는 게 좋을 것 같아요

2024-01-23 08:49 UTC, closed without merging